### ISSUE TITLE
Building Error

### ISSUE THREAD

**Issue by landosilva** [nomnomab/RaycastVisualization#4]
Hi, amazing package! However it has build issues.
`The name 'VisualPhysicsSettingsHandler' does not exist in the current context`
That's because the entire VisualPhysicsSettingsHandler is inside #if UNITY_EDITOR condition however the method OnLoad on the class Utils is using it.

**Comment by nomnomab** [comment]
Thanks for pointing this out, as I had forgotten to test a build! Fixing it now and an update should be out shortly.
