### ISSUE TITLE
VisualPhysics.Linecast not working as expected

### ISSUE THREAD

**Issue by riobruto** [nomnomab/RaycastVisualization#6]
The behavior of VisualPhysics.Linecast is not the same as Physics.Linecast when calling the method using parameters Vector3 start, vector3 end, out RaycastHit hit, LayerMask mask.  

these two methods seems to be working differently.

```csharp
public bool CastLineIssue()
{
    //This method seems to be interpreting "end" as a direction.
    Debug.DrawLine(transform.position, _physicsLinecastTarget.position, Color.yellow);
    return VisualPhysics.Linecast(transform.position, _visualLinecastTarget.position, out RaycastHit hit, _Mask);
}
public bool CastLine()
{
    Debug.DrawLine(transform.position, _physicsLinecastTarget.position, Color.yellow);
    return Physics.Linecast(transform.position, _visualLinecastTarget.position, out RaycastHit hit, _Mask);
}
```

![Unity_xTW93mBGhK](https://github.com/nomnomab/RaycastVisualization/assets/80372596/db52d7de-4a8d-4ce5-b86d-2c7af9485a9a)
![Unity_QBFU3JTwXC](https://github.com/nomnomab/RaycastVisualization/assets/80372596/538c346c-f40f-4fd9-8dfc-dea9e53a1529)

**Comment by nomnomab** [comment]
Thanks! Turns out a part of the linecast api was forgotten during a simplification pass I did a while back 👍
